source:
  label: DrugBank
  type: Chemical compound / Drug
  name: drugbank
  prefix: http://identifiers.org/drugbank

target:
  label: ChEBI
  type: Chemical compound / Drug
  name: chebi
  prefix: http://purl.obolibrary.org/obo/chebi#

link:
  label: Further information about the subject resource
  name: rdfs
  prefix: http://www.w3.org/2000/01/rdf-schema#
  predicate: seeAlso
  file: pair.tsv

reverse_link:
  label: Further information about the subject resource
  name: rdfs
  prefix: http://www.w3.org/2000/01/rdf-schema#
  predicate: seeAlso

update:
  frequency: Monthly
  method: wget https://go.drugbank.com/releases/5-1-8/downloads/all-full-database; unzip all-full-database; python3 make_pairs.py
